# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33e6461b6973465b7676ce9d30b23573a834f445b503a9ba3333809dea82e25bd0d99a4fe9e51f1a96fb43c1017e1a67c3884b70be0bed1c6752252640241d25

test:
  secret_key_base: b63f87cbb4289cfefb1b1335f09170e30a9cdf2915d42b9d0f917a1121c4b1c1cf7f58eaf74c5a269067c7fc48e53d3fc5549790500d87a27eebd202ff2c5299

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
